[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = true
# chain_id = 8453
# auto_detect_solc = true
solc_version = "0.8.24"
# evm_version = "cancun"
via_ir = false
cbor_metadata = false
use_literal_content = false
bytecode_hash = "none"
optimizer = true
optimizer_runs = 1000
libraries = []
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
always_use_create_2_factory = true
ignored_error_codes = ["license", "code-size", "shadowing", "unused-var", "unused-param"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
